package com.scm.scm20.repositories;

import com.scm.scm20.entities.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, String> {

    // Custom finder method generated by Spring Data JPA
    Optional<User> findByEmail(String email);

}